name: Verify Pull Request
on:
  pull_request:
    types: [ opened, synchronize, edited, reopened ]

jobs:
  verify_formatting:
    name: Flutter Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2
        name: Preparing Flutter SDK
        with:
          flutter-version: '3.19.4'
          channel: 'stable'
      - name: Format
        run: dart format --set-exit-if-changed lib
  analyze_code:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Downloading sources
      - uses: subosito/flutter-action@v2
        name: Preparing Flutter SDK
        with:
          flutter-version: '3.19.4'
          channel: 'stable'
      - name: Analyze
        run: flutter analyze lib